In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [4]:
a=np.array(50)
print(a)
print(a.ndim)
print(type(a))

50
0
<class 'numpy.ndarray'>


In [5]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(type(a))

[1 2 3 4]
1
<class 'numpy.ndarray'>


In [6]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.ndim)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
2
<class 'numpy.ndarray'>


In [7]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[8,9,10,10],[11,12,13,14]]])
print(a)
print(a.ndim)
print(type(a))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 8  9 10 10]
  [11 12 13 14]]]
3
<class 'numpy.ndarray'>


In [9]:
e=np.array([1,2.3,"python",7+8j,True,False])
print(e)
print(e.ndim)
print(type(e))

['1' '2.3' 'python' '(7+8j)' 'True' 'False']
1
<class 'numpy.ndarray'>


In [10]:
a=[1,2,3,4,8]
b=[4,5,6,7,9]
print(a+b)

[1, 2, 3, 4, 8, 4, 5, 6, 7, 9]


In [11]:
a=np.array([1,2,3,4,8])
b=np.array([4,5,6,7,9])
print(a+b)

[ 5  7  9 11 17]


In [12]:
c=np.sum(a)
print(c)

18


In [13]:
d=np.sum(b)
print(d)

31


In [14]:
e=np.mean(a)
print(e)

3.6


In [15]:
f=np.mean(b)
print(f)

6.2
