In [20]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 26.1.2 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [3]:
a=np.array(50)
print(a)
print(a.ndim)
print(type(a))

50
0
<class 'numpy.ndarray'>


In [4]:
a=np.array(50)
print(a)
print("The dimension is:",a.ndim)
print(type(a))

50
The dimension is: 0
<class 'numpy.ndarray'>


In [5]:
a=np.array([1,2,3,4])
print(a)
print("The dimension is:",a.ndim)
print(type(a))

[1 2 3 4]
The dimension is: 1
<class 'numpy.ndarray'>


In [6]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(type(a))

[1 2 3 4]
1
<class 'numpy.ndarray'>


In [7]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print("The dimension is:",a.ndim)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
The dimension is: 2
<class 'numpy.ndarray'>


In [8]:
a=np.array([[1,2,3,4],[5,6,7,8]])
print(a)
print(a.ndim)
print(type(a))

[[1 2 3 4]
 [5 6 7 8]]
2
<class 'numpy.ndarray'>


In [9]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(a)
print("The dimension is:",a.ndim)
print(type(a))

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
The dimension is: 3
<class 'numpy.ndarray'>


In [15]:
a=np.array([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[5,6,7,8]]])
print(a)
print(a.ndim)
print(type(a))

[[[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]
3
<class 'numpy.ndarray'>


31-07-2026

In [12]:
e=np.array([3,4.5,"python",4+8j,True,False])
print(e)
print(type(e))
print(e.ndim)

['3' '4.5' 'python' '(4+8j)' 'True' 'False']
<class 'numpy.ndarray'>
1


In [13]:
a=[1,2,3,4,5,6]
b=[6,7,8,9,10,11]
print(a+b)

[1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11]


In [14]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a+b)

[ 6  8 10 12 14]


In [16]:
c=np.sum(a)
print(c)

72


In [17]:
d=np.sum(b)
print(d)

35


In [18]:
e=np.mean(a)
print(e)

4.5


In [19]:
f=np.mean(b)
print(f)

7.0
